
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTER_ERROR = "CHARACTER_ERROR";
export const CHARACTER_NAME = "CHARACTER_NAME";
export const CHARACTER_HEIGHT = "CHARACTER_HEIGHT";
export const CHARACTER_SKIN_COLOR = "CHARACTER_SKIN_COLOR";
export const CHARACTER_HAIR_COLOR = "CHARACTER_HAIR_COLOR";



